### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by omnipotenttom** [yashbhalgat/HashNeRF-pytorch#41]
Traceback (most recent call last):
  File "run_nerf.py", line 992, in <module>
    train()
  File "run_nerf.py", line 660, in train
    images, poses, render_poses, hwf, i_split, bounding_box = load_blender_data(args.datadir, args.half_res, args.testskip)
  File "/home/shuow/HashNeRF-pytorch/load_blender.py", line 89, in load_blender_data
    bounding_box = get_bbox3d_for_blenderobj(metas["train"], H, W, near=2.0, far=6.0)
  File "/home/shuow/HashNeRF-pytorch/utils.py", line 41, in get_bbox3d_for_blenderobj
    rays_o, rays_d = get_rays(directions, c2w)
  File "/home/shuow/HashNeRF-pytorch/ray_utils.py", line 46, in get_rays
    rays_d = directions @ c2w[:3, :3].T # (H, W, 3)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

I tried sending directions and c2w to cuda, but still got an error. why  found  two devices?

**Comment by omnipotenttom** [comment]
directions.device is cuda，while  c2w‘sdevice is cpu.  Use c2w = c2w.to("cuda:0") to solve this problem
